services:
  - type: web
    name: qrcode-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PRODUCTION
        value: true
      - key: PYTHON_VERSION
        value: 3.11.11
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
